# Урок 5. Домашнее задание

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [34]:
# 1

import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [35]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [36]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [37]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [38]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [39]:
# Убедимся, что она действительно ортогональна
print(np.dot(U.T, U))

[[ 1.  0. -0.  0. -0.]
 [ 0.  1.  0.  0.  0.]
 [-0.  0.  1. -0. -0.]
 [ 0.  0. -0.  1. -0.]
 [-0.  0. -0. -0.  1.]]


In [40]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [41]:
# Убедимся, что она действительно ортогональна
print(np.dot(V.T, V))

[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]


In [42]:
# Проведем проверку
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


In [43]:
# 2

from numpy.linalg import norm

print(f'Евклидова норма матрицы А:\n{norm(A, ord=2)}')

Евклидова норма матрицы А:
8.824868854820444


Действительно убеждаюсь, что евклидова норма матрицы равна максимальному сингулярному числу $\mu_{max}$ = $\mu_{1}$ = 8.82. 

In [44]:
print(f'Норма Фробениуса матрицы А:\n{norm(A, ord="fro")}')

Норма Фробениуса матрицы А:
11.045361017187261


In [45]:
np.sqrt(1 + 2**2 + 5**2 + 3**2 + 4**2 + 2**2 + 1**2 + 6**2 + 5**2 +1**2)

11.045361017187261

In [46]:
np.sqrt(8.82**2 + 6.14**2 + 2.53**2)

11.04051176350082

Действительно убеждаюсь, что норма Фробениуса равна корню квадратному из суммы квадратов элементов матрицы и равна корню квадратному из суммы квадратов сингулярных чисел матрицы. 