# Урок 2, часть 1. Домашнее задание

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [1]:
import numpy as np

In [2]:
# 2

a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица С = A + B\n{a + b}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]


In [3]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{A.dot(B)}')
print(f'Матрица BA\n{B.dot(A)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BA
[[ 1 -8]
 [15  0]]


In [4]:
# 3

a = np.array([[1, 7], [3, -6]])
k = 3

print(f'Матрица А\n{a}\n')
print(f'Матрица 3*А\n{k * a}')

b = np.array([[0, 5], [2, -1]])
l = -2

print(f'Матрица B\n{b}\n')
print(f'Матрица -2*B\n{l * b}')

c = np.array([[2, -4], [1, 1]])
m = 4

print(f'Матрица C\n{c}\n')
print(f'Матрица 4*C\n{m * c}')

print(f'Линейная комбинация 3*А-2*B+4*C\n{(k * a)+(l * b)+(m * c)}')

Матрица А
[[ 1  7]
 [ 3 -6]]

Матрица 3*А
[[  3  21]
 [  9 -18]]
Матрица B
[[ 0  5]
 [ 2 -1]]

Матрица -2*B
[[  0 -10]
 [ -4   2]]
Матрица C
[[ 2 -4]
 [ 1  1]]

Матрица 4*C
[[  8 -16]
 [  4   4]]
Линейная комбинация 3*А-2*B+4*C
[[ 11  -5]
 [  9 -12]]


In [5]:
# 4

a = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Исходная матрица A:\n{a}')
print(f'Транспонированная матрица AT:\n{a.T}')

print(f'Матрица (корреляционная) AAT\n{a.dot(a.T)}')

print(f'Матрица (ковариационная) ATA\n{(a.T).dot(a)}')

Исходная матрица A:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица AT:
[[ 4  5  2]
 [ 1 -2  3]]
Матрица (корреляционная) AAT
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица (ковариационная) ATA
[[45  0]
 [ 0 14]]


In [6]:
# 5*

def multiplicate_matrix(left,right):
    try: 
        left.shape[1]==right.shape[0]
        result=[]
        temp=[]
        s=0
        for i in range(left.shape[0]):
            for j in range(right.shape[1]):
                for k in range(right.shape[0]):
                    s+=left[i][k]*right[k][j]
                temp.append(s)
                s=0
            result.append(temp)
            temp=[]
        return np.array(result)
    except Exception:
        print('Произведение матриц таких размеров не определено!')

In [7]:
a = np.array([[4, 1], [5, -2], [2, 3]])
b = a.T

multiplicate_matrix(a,b)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [8]:
a = np.array([[4, 1], [5, -2], [2, 3], [0, 1]])
b = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

multiplicate_matrix(a,b)

Произведение матриц таких размеров не определено!
