# Урок 3. Домашнее задание

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [4]:
# 1

a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v}\n')

print(f'v1\n{v.T[1]}')
print(f'v1\n{v[:, 1]}')
print(f'\n{v.T[1].dot(v.T[1])}')

Матрица A:
[[-1 -6]
 [ 2  6]]

Собственные значения:
[2. 3.]

Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]

v1
[ 0.83 -0.55]
v1
[ 0.83 -0.55]

1.0


In [5]:
# 2

a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v}\n')

print(f'v1\n{v.T[1]}')
print(f'v1\n{v[:, 1]}')
print(f'\n{v.T[1].dot(v.T[1])}')

Матрица A:
[[-1  0]
 [ 0 -1]]

Собственные значения:
[-1. -1.]

Собственные векторы:
[[1. 0.]
 [0. 1.]]

v1
[0. 1.]
v1
[0. 1.]

1.0


In [6]:
# 3

a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v}\n')

print(f'v1\n{v.T[1]}')
print(f'v1\n{v[:, 1]}')
print(f'\n{v.T[1].dot(v.T[1])}')

Матрица A:
[[ 1  1]
 [-1  3]]

Собственные значения:
[2. 2.]

Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]

v1
[-0.71 -0.71]
v1
[-0.71 -0.71]

1.0


In [7]:
# 4

a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v}\n')

print(f'v1\n{v.T[1]}')
print(f'v1\n{v[:, 1]}')
print(f'\n{v.T[1].dot(v.T[1])}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]

Собственные значения:
[ 3. -3.  3.]

Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]

v1
[-0.71  0.71  0.  ]
v1
[-0.71  0.71  0.  ]

1.0
