# Урок 4, часть 1. Домашнее задание

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

In [21]:
import numpy as np

In [22]:
# 1

a = np.array([[1, 1, -1, -2], [2, 1, -1, 1], [1, 1, -3, 1]])
b = np.array([0, -2, 4])

np.linalg.solve(a, b)

LinAlgError: ignored

In [ ]:
import scipy as sp

In [ ]:
sp.linalg.solve(a, b)

In [23]:
# 2

# а)

n = 3

a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
r = np.linalg.matrix_rank(a)

print(f'Матрица:\n{a}')
print(f'Ранг матрицы: {r}\n')

Матрица:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]
Ранг матрицы: 3



In [24]:
a_ = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
r_ = np.linalg.matrix_rank(a)

print(f'Матрица:\n{a_}')
print(f'Ранг матрицы: {r_}\n')

Матрица:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]
Ранг матрицы: 3



In [25]:
r == r_ == n

True

In [26]:
# б)

n = 3

a = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
r = np.linalg.matrix_rank(a)

print(f'Матрица:\n{a}')
print(f'Ранг матрицы: {r}\n')

Матрица:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]
Ранг матрицы: 1



In [27]:
a_ = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
r_ = np.linalg.matrix_rank(a)

print(f'Матрица:\n{a_}')
print(f'Ранг матрицы: {r_}\n')

Матрица:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]
Ранг матрицы: 1



In [28]:
r == r_ == n

False

In [29]:
# в)

n = 3

a = np.array([[1, 2, 5], [3, 1, -8]])
r = np.linalg.matrix_rank(a)

print(f'Матрица:\n{a}')
print(f'Ранг матрицы: {r}\n')

Матрица:
[[ 1  2  5]
 [ 3  1 -8]]
Ранг матрицы: 2



In [30]:
a_ = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
r_ = np.linalg.matrix_rank(a)

print(f'Матрица:\n{a_}')
print(f'Ранг матрицы: {r_}\n')

Матрица:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]
Ранг матрицы: 2



In [31]:
r == r_ == n

False

In [32]:
# 3

n = 4

a = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
r = np.linalg.matrix_rank(a)

print(f'Матрица:\n{a}')
print(f'Ранг матрицы: {r}\n')

Матрица:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]
Ранг матрицы: 4



In [33]:
a_ = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
r_ = np.linalg.matrix_rank(a)

print(f'Матрица:\n{a_}')
print(f'Ранг матрицы: {r_}\n')

Матрица:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]
Ранг матрицы: 4



In [34]:
r == r_ == n

True

4

Ответ: соотношение 3a+2b-c=0. 