# Урок 4, часть 2. Домашнее задание

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    
__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [15]:
import numpy as np

In [16]:
# 1

# а)

a = np.array([[1, -2], [3, -4]])
b = np.array([1, 7])

np.linalg.solve(a, b)

array([5., 2.])

In [17]:
# б) 

a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])

np.linalg.solve(a, b)

array([ 2., -1.,  1.])

In [18]:
# 2

# а)

from scipy.linalg import lu
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
p, l, u = lu(A)

l

array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.33333333, 0.8       , 1.        ]])

Почему-то не совпадает с решением на листке. 

In [19]:
# б)

A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
p, l, u = lu(A)

l

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ],
       [ 0.75      , -0.25      ,  1.        ,  0.        ],
       [ 0.25      ,  0.75      , -0.17073171,  1.        ]])

Почему-то не совпадает с решением на листке.

In [20]:
# 3

a = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

np.linalg.solve(a, b)

array([-1.,  0.,  1.])

In [21]:
# 4

a = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

np.linalg.solve(a, b)

array([ 6., -5., -4.])

In [22]:
# 5*

def kramer_method(a, b):
    
    det_a = np.linalg.det(a)
    
    if det_a != 0 and a.shape[0] == a.shape[1]:
        M = np.array([])
        X = []
        for j in range(len(a)):
            M = a.copy()
            M[:, j] = b
            X.append(round(np.linalg.det(M)/det_a)) 
        return X
    else:
        return False

In [23]:
a = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

print(kramer_method(a, b))

[6, -5, -4]
